name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Run Selenium tests
      run: |
        # Iterar sobre cada script de prueba y ejecutarlo individualmente
        for script in campo_email.py campo_nombre.py campo_phone.py; do
          python "/home/runner/work/Selenium/Selenium/C/Users/santiago.gauna/Desktop/Webdriver/Fomulario/Validaciones de campos/$script"
        done
